name: CI-Stylelint

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "main and develop" branch
  pull_request:
    branches: ['main', 'develop', 'develop-*']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  stylelint:
    name: Validate Stylelint
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: ${{!contains(github.event.commits[0].message, 'PATCH') || !contains(github.event.commits[0].message, 'MINOR') || !contains(github.event.commits[0].message, 'MAJOR') || !contains(github.event.commits[0].message, 'RELEASE')}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: '>=22.20'
      - run: npm install -g corepack && corepack enable

      - name: Print versions
        run: |
          git --version
          node --version
          npm --version

      - name: Run Stylelint
        run: |
          yarn
          yarn validate:css
